# Coding Exercise 4: Dataset Splitting and Feature Scaling

1: Import necessary Python libraries: pandas, train_test_split from sklearn.model_selection, and StandardScaler from sklearn.preprocessing.

2: Load the Iris dataset using Pandas read.csv. Dataset name is iris.csv.

3: Use train_test_split to split the dataset into an 80-20 training-test set.

4: Apply random_state with 42 value in train_test_split function for reproducible results.

5: Print X_train, X_test, Y_train, and Y_test to understand the dataset split.

6: Use StandardScaler to apply feature scaling on the training and test sets.

7: Print scaled training and test sets to verify feature scaling.

# Importing the libraries

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Importing the dataset

In [4]:
df = pd.read_csv('datasets/iris.csv')
print(df.head())
print(df.info())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
dtypes: float

In [17]:
# Separate features and target
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

# Splitting the dataset into the Training Set and Test Set

In [18]:
# Split the dataset into an 80-20 training-test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [19]:
print(X_train)

[[6.1 3.  4.6 1.4]
 [7.7 3.  6.1 2.3]
 [5.6 2.5 3.9 1.1]
 [6.4 2.8 5.6 2.1]
 [5.8 2.8 5.1 2.4]
 [5.3 3.7 1.5 0.2]
 [5.5 2.3 4.  1.3]
 [5.2 3.4 1.4 0.2]
 [6.5 2.8 4.6 1.5]
 [6.7 2.5 5.8 1.8]
 [6.8 3.  5.5 2.1]
 [5.1 3.5 1.4 0.3]
 [6.  2.2 5.  1.5]
 [6.3 2.9 5.6 1.8]
 [6.6 2.9 4.6 1.3]
 [7.7 2.6 6.9 2.3]
 [5.7 3.8 1.7 0.3]
 [5.  3.6 1.4 0.2]
 [4.8 3.  1.4 0.3]
 [5.2 2.7 3.9 1.4]
 [5.1 3.4 1.5 0.2]
 [5.5 3.5 1.3 0.2]
 [7.7 3.8 6.7 2.2]
 [6.9 3.1 5.4 2.1]
 [7.3 2.9 6.3 1.8]
 [6.4 2.8 5.6 2.2]
 [6.2 2.8 4.8 1.8]
 [6.  3.4 4.5 1.6]
 [7.7 2.8 6.7 2. ]
 [5.7 3.  4.2 1.2]
 [4.8 3.4 1.6 0.2]
 [5.7 2.5 5.  2. ]
 [6.3 2.7 4.9 1.8]
 [4.8 3.  1.4 0.1]
 [4.7 3.2 1.3 0.2]
 [6.5 3.  5.8 2.2]
 [4.6 3.4 1.4 0.3]
 [6.1 3.  4.9 1.8]
 [6.5 3.2 5.1 2. ]
 [6.7 3.1 4.4 1.4]
 [5.7 2.8 4.5 1.3]
 [6.7 3.3 5.7 2.5]
 [6.  3.  4.8 1.8]
 [5.1 3.8 1.6 0.2]
 [6.  2.2 4.  1. ]
 [6.4 2.9 4.3 1.3]
 [6.5 3.  5.5 1.8]
 [5.  2.3 3.3 1. ]
 [6.3 3.3 6.  2.5]
 [5.5 2.5 4.  1.3]
 [5.4 3.7 1.5 0.2]
 [4.9 3.1 1.5 0.2]
 [5.2 4.1 1.

In [20]:
print(X_test)

[[5.8 4.  1.2 0.2]
 [5.1 2.5 3.  1.1]
 [6.6 3.  4.4 1.4]
 [5.4 3.9 1.3 0.4]
 [7.9 3.8 6.4 2. ]
 [6.3 3.3 4.7 1.6]
 [6.9 3.1 5.1 2.3]
 [5.1 3.8 1.9 0.4]
 [4.7 3.2 1.6 0.2]
 [6.9 3.2 5.7 2.3]
 [5.6 2.7 4.2 1.3]
 [5.4 3.9 1.7 0.4]
 [7.1 3.  5.9 2.1]
 [6.4 3.2 4.5 1.5]
 [6.  2.9 4.5 1.5]
 [4.4 3.2 1.3 0.2]
 [5.8 2.6 4.  1.2]
 [5.6 3.  4.5 1.5]
 [5.4 3.4 1.5 0.4]
 [5.  3.2 1.2 0.2]
 [5.5 2.6 4.4 1.2]
 [5.4 3.  4.5 1.5]
 [6.7 3.  5.  1.7]
 [5.  3.5 1.3 0.3]
 [7.2 3.2 6.  1.8]
 [5.7 2.8 4.1 1.3]
 [5.5 4.2 1.4 0.2]
 [5.1 3.8 1.5 0.3]
 [6.1 2.8 4.7 1.2]
 [6.3 2.5 5.  1.9]]


# Feature Scaling

In [23]:
# Apply feature scaling on the training and test sets
sc = StandardScaler()
X_train[:, :] = sc.fit_transform(X_train[:, :])
X_test[:, :] = sc.transform(X_test[:, :])

In [25]:
# Print the scaled training and test sets
print(X_train)

[[ 0.31553662 -0.04578885  0.44767531  0.23380268]
 [ 2.2449325  -0.04578885  1.29769171  1.39742892]
 [-0.2873996  -1.24028061  0.05100098 -0.15407273]
 [ 0.67729835 -0.52358555  1.01435291  1.13884531]
 [-0.04622511 -0.52358555  0.73101411  1.52672073]
 [-0.64916132  1.62649961 -1.30902526 -1.31769898]
 [-0.40798684 -1.71807731  0.10766874  0.10451088]
 [-0.76974857  0.90980456 -1.36569302 -1.31769898]
 [ 0.79788559 -0.52358555  0.44767531  0.36309449]
 [ 1.03906007 -1.24028061  1.12768843  0.7509699 ]
 [ 1.15964732 -0.04578885  0.95768515  1.13884531]
 [-0.89033581  1.14870291 -1.36569302 -1.18840717]
 [ 0.19494938 -1.95697567  0.67434635  0.36309449]
 [ 0.5567111  -0.2846872   1.01435291  0.7509699 ]
 [ 0.91847283 -0.2846872   0.44767531  0.10451088]
 [ 2.2449325  -1.00138226  1.75103379  1.39742892]
 [-0.16681235  1.86539796 -1.19568974 -1.18840717]
 [-1.01092305  1.38760126 -1.36569302 -1.31769898]
 [-1.25209754 -0.04578885 -1.36569302 -1.18840717]
 [-0.76974857 -0.76248391  0.05

In [26]:
print(X_test)

[[-0.04622511  2.34319467 -1.47902854 -1.31769898]
 [-0.89033581 -1.24028061 -0.45900886 -0.15407273]
 [ 0.91847283 -0.04578885  0.33433978  0.23380268]
 [-0.52857408  2.10429632 -1.42236078 -1.05911537]
 [ 2.48610699  1.86539796  1.46769499  1.00955351]
 [ 0.5567111   0.6709062   0.50434307  0.49238629]
 [ 1.28023456  0.1931095   0.73101411  1.39742892]
 [-0.89033581  1.86539796 -1.08235422 -1.05911537]
 [-1.37268478  0.43200785 -1.2523575  -1.31769898]
 [ 1.28023456  0.43200785  1.07102067  1.39742892]
 [-0.2873996  -0.76248391  0.22100426  0.10451088]
 [-0.52857408  2.10429632 -1.19568974 -1.05911537]
 [ 1.52140905 -0.04578885  1.18435619  1.13884531]
 [ 0.67729835  0.43200785  0.39100755  0.36309449]
 [ 0.19494938 -0.2846872   0.39100755  0.36309449]
 [-1.73444651  0.43200785 -1.42236078 -1.31769898]
 [-0.04622511 -1.00138226  0.10766874 -0.02478093]
 [-0.2873996  -0.04578885  0.39100755  0.36309449]
 [-0.52857408  0.90980456 -1.30902526 -1.05911537]
 [-1.01092305  0.43200785 -1.47